services:
  postgres:
    profiles: ["default", "dev"]
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=bankdata25
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bankdata"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    profiles: ["default"]
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  db_data:
