micronaut:
  application:
    name: bankdata
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"


flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

jooq:
  datasources:
    default:
      configuration:
        settings:
          executeLogging: true