/*
 * This file is generated by jOOQ.
 */
package dk.ckrag.jooq.tables.records;


import dk.ckrag.jooq.tables.Transaction;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.transaction.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transaction.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.transaction.from_account_id</code>.
     */
    public void setFromAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transaction.from_account_id</code>.
     */
    public Long getFromAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.transaction.to_account_id</code>.
     */
    public void setToAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transaction.to_account_id</code>.
     */
    public Long getToAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.transaction.amount</code>.
     */
    public void setAmount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transaction.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.transaction.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.transaction.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION);
    }

    /**
     * Create a detached, initialised TransactionRecord
     */
    public TransactionRecord(Long id, Long fromAccountId, Long toAccountId, Integer amount, OffsetDateTime createdAt) {
        super(Transaction.TRANSACTION);

        setId(id);
        setFromAccountId(fromAccountId);
        setToAccountId(toAccountId);
        setAmount(amount);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
