/*
 * This file is generated by jOOQ.
 */
package dk.ckrag.jooq.tables;


import dk.ckrag.jooq.Keys;
import dk.ckrag.jooq.Public;
import dk.ckrag.jooq.tables.Account.AccountPath;
import dk.ckrag.jooq.tables.records.TransactionRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Transaction extends TableImpl<TransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.transaction</code>
     */
    public static final Transaction TRANSACTION = new Transaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionRecord> getRecordType() {
        return TransactionRecord.class;
    }

    /**
     * The column <code>public.transaction.id</code>.
     */
    public final TableField<TransactionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.transaction.from_account_id</code>.
     */
    public final TableField<TransactionRecord, Long> FROM_ACCOUNT_ID = createField(DSL.name("from_account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction.to_account_id</code>.
     */
    public final TableField<TransactionRecord, Long> TO_ACCOUNT_ID = createField(DSL.name("to_account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction.amount</code>.
     */
    public final TableField<TransactionRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.transaction.created_at</code>.
     */
    public final TableField<TransactionRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Transaction(Name alias, Table<TransactionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Transaction(Name alias, Table<TransactionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.transaction</code> table reference
     */
    public Transaction(String alias) {
        this(DSL.name(alias), TRANSACTION);
    }

    /**
     * Create an aliased <code>public.transaction</code> table reference
     */
    public Transaction(Name alias) {
        this(alias, TRANSACTION);
    }

    /**
     * Create a <code>public.transaction</code> table reference
     */
    public Transaction() {
        this(DSL.name("transaction"), null);
    }

    public <O extends Record> Transaction(Table<O> path, ForeignKey<O, TransactionRecord> childPath, InverseForeignKey<O, TransactionRecord> parentPath) {
        super(path, childPath, parentPath, TRANSACTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TransactionPath extends Transaction implements Path<TransactionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TransactionPath(Table<O> path, ForeignKey<O, TransactionRecord> childPath, InverseForeignKey<O, TransactionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TransactionPath(Name alias, Table<TransactionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TransactionPath as(String alias) {
            return new TransactionPath(DSL.name(alias), this);
        }

        @Override
        public TransactionPath as(Name alias) {
            return new TransactionPath(alias, this);
        }

        @Override
        public TransactionPath as(Table<?> alias) {
            return new TransactionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TransactionRecord, Long> getIdentity() {
        return (Identity<TransactionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TransactionRecord> getPrimaryKey() {
        return Keys.TRANSACTION_PKEY;
    }

    @Override
    public List<ForeignKey<TransactionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRANSACTION__FK_FROM_ACCOUNT, Keys.TRANSACTION__FK_TO_ACCOUNT);
    }

    private transient AccountPath _fkFromAccount;

    /**
     * Get the implicit join path to the <code>public.account</code> table, via
     * the <code>fk_from_account</code> key.
     */
    public AccountPath fkFromAccount() {
        if (_fkFromAccount == null)
            _fkFromAccount = new AccountPath(this, Keys.TRANSACTION__FK_FROM_ACCOUNT, null);

        return _fkFromAccount;
    }

    private transient AccountPath _fkToAccount;

    /**
     * Get the implicit join path to the <code>public.account</code> table, via
     * the <code>fk_to_account</code> key.
     */
    public AccountPath fkToAccount() {
        if (_fkToAccount == null)
            _fkToAccount = new AccountPath(this, Keys.TRANSACTION__FK_TO_ACCOUNT, null);

        return _fkToAccount;
    }

    @Override
    public Transaction as(String alias) {
        return new Transaction(DSL.name(alias), this);
    }

    @Override
    public Transaction as(Name alias) {
        return new Transaction(alias, this);
    }

    @Override
    public Transaction as(Table<?> alias) {
        return new Transaction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(String name) {
        return new Transaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Name name) {
        return new Transaction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Table<?> name) {
        return new Transaction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transaction where(Condition condition) {
        return new Transaction(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transaction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transaction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transaction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transaction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transaction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transaction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Transaction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transaction whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Transaction whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
