CREATE TABLE account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount INT NOT NULL
);

CREATE TABLE transaction (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    from_account_id BIGINT NOT NULL,
    to_account_id BIGINT NOT NULL,
    amount INT NOT NULL,
    CONSTRAINT fk_from_account
        FOREIGN KEY (from_account_id)
        REFERENCES account (id),
    CONSTRAINT fk_to_account
        FOREIGN KEY (to_account_id)
        REFERENCES account (id)
);
