/*
 * This file is generated by jOOQ.
 */
package dk.ckrag.jooq;


import dk.ckrag.jooq.tables.Account;
import dk.ckrag.jooq.tables.Transaction;
import dk.ckrag.jooq.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
